name: Prepare Frontend

on:
  workflow_call:
    inputs:
      node_version:
        description: "Node.js version to use"
        required: true
        type: string

jobs:
  prepare-frontend:
    name: Prepare Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: show files
        run: |
          ls -l

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: show files
        run: |
          ls -l

      - name: Set version
        run: ./.github/scripts/set-version.sh

      - name: show files
        run: |
          ls -l
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --fund=false

      - name: show files
        run: |
          ls -l

#      - name: Cache node_modules
#        uses: actions/cache/save@v4
#        with:
#          path: |
#            ~/.npm/
#            node_modules/
#            package-lock.json
#          key: npm-${{ github.sha }}